export const REVIEWS = [
  {
    id: '1',
    outletId: 'outlet-1',
    outletName: 'ZamZam Bakery – Calicut',
    rating: 5,
    comment: 'Amazing taste and very fresh!',
    customer: 'Rahul',
    date: '2025-01-12',
  },
  {
    id: '2',
    outletId: 'outlet-2',
    outletName: 'ZamZam Cafe – Kochi',
    rating: 3,
    comment: 'Good food but service was slow.',
    customer: 'Anjali',
    date: '2025-01-14',
  },
  {
    id: '3',
    outletId: 'outlet-1',
    outletName: 'ZamZam Bakery – Calicut',
    rating: 4,
    comment: 'Nice ambience, will visit again.',
    customer: 'Faizal',
    date: '2025-01-15',
  },
  {
    id: '4',
    outletId: 'outlet-3',
    outletName: 'ZamZam Bakery – Malappuram',
    rating: 2,
    comment: 'Not satisfied with quality.',
    customer: 'Sana',
    date: '2025-01-16',
  },
  {
    id: '5',
    outletId: 'outlet-2',
    outletName: 'ZamZam Cafe – Kochi',
    rating: 5,
    comment: 'Loved it! Best cafe in town.',
    customer: 'Arjun',
    date: '2025-01-17',
  },
];
